Add SSL Support - completion of PR#5
openresty/lua-resty-upstream-healthcheck pull request #36
Opened 2017-01-27 17:42 UTC by ElvinEfendi

This PR is based on the work done at https://github.com/openresty/lua-resty-upstream-healthcheck/pull/5.

It adds SSL support and addresses all the comments(tests and session reuse) made in the original PR.

One significant modification to the original PR is that now, the health check will fail if `ssl_verify = true` and the certificate verification fails.

/r @agentzh

2017-02-02 14:48 UTC, ElvinEfendi commented
ping

2017-02-10 18:48 UTC, charlescng commented
@agentzh Can you review?

2017-02-11 21:23 UTC, agentzh requested changes

2017-02-11 21:23 UTC, agentzh commented on lib/resty/upstream/healthcheck.lua
> +        session, err = sock:sslhandshake(ctx.session, name, ctx.ssl_verify)
Is `session` a global Lua variable? We should declare it as a `local`.

2017-02-11 21:23 UTC, agentzh commented on t/sanity.t
> +init_worker_by_lua '
We should use `init_worker_by_lua_block` here for newly added tests.

2017-02-11 21:23 UTC, agentzh commented on t/sanity.t
> +        content_by_lua '
We should use `content_by_lua_block` in newly added tests. Please fix other similar places.

2017-02-11 21:24 UTC, agentzh commented
Also, please rebase to the latest git master.

2017-02-11 21:25 UTC, agentzh commented on lib/resty/upstream/healthcheck.lua
> +        session, err = sock:sslhandshake(ctx.session, name, ctx.ssl_verify)
Better use the `lua-releng` script of `nginx-devel-utils` to check your Lua code. I'm getting the following errors by running this tool against your branch:

```
$ lua-releng
lib/resty/upstream/healthcheck.lua: 0.03 (0.03)
Checking use of Lua global variables in file lib/resty/upstream/healthcheck.lua...
	op no.	line	instruction	args	; code
	53	[237]	SETGLOBAL	11 -14	; session
	54	[238]	GETGLOBAL	11 -14	; session
	73	[244]	GETGLOBAL	11 -14	; session
Checking line length exceeding 80...
```

So apparently the `session` is a misused Lua global variable.

2017-02-11 21:26 UTC, agentzh commented
@ElvinEfendi Thank you for your patch! Please take care of my comments above. Thanks!

2017-02-15 19:27 UTC, ElvinEfendi commented
@agentzh thanks for reviewing, I addressed your comments.

> Also, please rebase to the latest git master.

I don't see any conflict with the upstream master(there were some initially but those have been sycned to this branch already). And all the commits from it are already included in this branch. Why do you think this branch is not in sync with the upstream master?

2017-02-22 18:48 UTC, ElvinEfendi commented
@agentzh any more comment on this PR?

2017-02-22 23:15 UTC, ElvinEfendi commented
By default `peer.name`(an entry defined inside upstream block as `<host>:<port>`) is being passed to `tcpsock:sslhandshake` function as `server_name` which is used to validate the server name specified in the server certificate sent from the remote when `ssl_verify` is `true`. Refer to https://github.com/openresty/lua-nginx-module#tcpsocksslhandshake for more information. This is a constraint when we want to share a single server certificate to do SSL health check between multiple peers. Therefore I added TEST 20 and 21 to make `ssl_verify` option's behaviour more clear and added a new functionality that lets users to override `peer.name` with a custom name set during the initialization. TEST 21 covers the new functionality. These changes are added in commit: https://github.com/openresty/lua-resty-upstream-healthcheck/pull/36/commits/ce88ef0ffc8e2230882bbb7bd83247a35e9061c6

2017-06-30 02:05 UTC, solio commented
why this pr has not bean merged？
这个ssl support什么时候能合到主干上？

2017-07-10 17:51 UTC, agentzh commented
@solio This is still in my review queue. Sorry for the delay on my side.

2017-07-10 17:53 UTC, agentzh commented
@ElvinEfendi Will you please rebase to the latest git master? I'm seeing merge conflicts while rebasing it myself:

```
$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: add ssl support
Using index info to reconstruct a base tree...
M	README.markdown
M	lib/resty/upstream/healthcheck.lua
Falling back to patching base and 3-way merge...
Auto-merging lib/resty/upstream/healthcheck.lua
CONFLICT (content): Merge conflict in lib/resty/upstream/healthcheck.lua
Auto-merging README.markdown
error: Failed to merge in the changes.
Patch failed at 0001 add ssl support
The copy of the patch that failed is found in: .git/rebase-apply/patch
```

Thanks! And sorry for the delay on my side.

2017-07-11 03:01 UTC, ElvinEfendi commented
> Will you please rebase to the latest git master? I'm seeing merge conflicts while rebasing it myself:

Hmm I don't know why does it show conflict. There's no commit in the upstream after https://github.com/openresty/lua-resty-upstream-healthcheck/commit/69751de70d5ac6ab84947e8e074b7a14715fdb02 which is already in downstream as well https://github.com/Shopify/lua-resty-upstream-healthcheck/commit/69751de70d5ac6ab84947e8e074b7a14715fdb02.

2017-07-11 03:11 UTC, ElvinEfendi commented
I'd also like to highlight that https://github.com/openresty/lua-resty-upstream-healthcheck/pull/36/commits/6731f959d146264e8ba1b5adbd41968deb0ae92e is not related to this PR, it is just included here because the downstream is Shopify fork's _master_.

I can create another branch in Shopify's fork without that commit and make another PR if you don't want to merge that last unrelated commit.

2017-07-12 02:55 UTC, agentzh commented
@ElvinEfendi Cool, thanks!

2017-07-17 14:04 UTC, berlincount commented
hmmm, may I ping on this PR? :)

2018-02-20 15:50 UTC, pavelnemirovsky commented
@agentzh when do u plan to merge it? Thx

2018-02-26 00:40 UTC, agentzh commented
Sorry, we haven't had the time to look at this. Been busy with other things with higher priority.

2018-02-26 00:42 UTC, agentzh commented
@dndx @spacewander Please help review this PR once you have a chance. Thanks!

2018-06-12 11:17 UTC, igbun commented
Hi,
Is there any update regarding this PR?

2019-03-25 10:41 UTC, Locoking commented
Dears, any update on this feature?

2020-05-25 14:00 UTC, TWHOI commented
+1 year :-/
Would be nice to have this merged.

2020-05-25 16:46 UTC, doujiang24 commented
@rainingmaster do you have time to take a look at this PR?

2021-08-04 20:29 UTC, leandromoreira commented
@agentzh is there any plan to merge this ?

2021-08-05 11:52 UTC, leandromoreira commented
Hi  @ElvinEfendi did you publish a rock with these changes? If you didn't, I'm thinking to keep a `lua-resty-upstream-healthcheck-ssl` repo patching your changes to the main branch of this repo, what do you think?

2021-08-06 20:31 UTC, leandromoreira commented
I copied this PR and released it as a rock https://github.com/globocom/lua-resty-upstream-healthcheck

2021-08-09 17:03 UTC, xiaocang requested changes

2025-03-29 14:30 UTC, ElvinEfendi commented
I'd forgotten about this not planning on continuing. If this is still useful for some, please fork away and make another PR.

2025-03-29 14:30 UTC, closed without merging