Add prometheus metrics format status with tests
openresty/lua-resty-upstream-healthcheck pull request #87
Opened 2022-07-07 20:17 UTC by Freggy

Hello, I followed your advise you left [here](https://github.com/openresty/lua-resty-upstream-healthcheck/pull/77#issuecomment-1173070778) on #77 and added tests for this functionality.

2022-07-08 03:48 UTC, zhuizhuhaomeng requested changes

2022-07-08 03:48 UTC, zhuizhuhaomeng commented on lib/resty/upstream/healthcheck.lua
> +    bits[idx] = "# HELP nginx_upstream_status_info The running staus of nginx upstream"
```suggestion
    bits[idx] = "# HELP nginx_upstream_status_info The running status of nginx upstream"
```

2022-07-08 03:48 UTC, zhuizhuhaomeng commented on lib/resty/upstream/healthcheck.lua
> +            idx = idx+1
```suggestion
            idx = idx + 1
```

2022-07-08 03:48 UTC, zhuizhuhaomeng commented on lib/resty/upstream/healthcheck.lua
> +    idx = idx+1
```suggestion
    idx = idx + 1
```

2022-07-08 03:48 UTC, zhuizhuhaomeng commented on lib/resty/upstream/healthcheck.lua
> +            idx = idx+1
```suggestion
            idx = idx + 1
```

2022-07-08 07:01 UTC, Freggy commented on lib/resty/upstream/healthcheck.lua
> +            idx = idx+1
see https://github.com/openresty/lua-resty-upstream-healthcheck/pull/87/commits/6b0fde522f679a62ce453f77fdfa75dae35523e1

2022-07-08 07:02 UTC, Freggy commented on lib/resty/upstream/healthcheck.lua
> +    idx = idx+1
see https://github.com/openresty/lua-resty-upstream-healthcheck/pull/87/commits/6b0fde522f679a62ce453f77fdfa75dae35523e1

2022-07-08 07:02 UTC, Freggy commented on lib/resty/upstream/healthcheck.lua
> +            idx = idx+1
see https://github.com/openresty/lua-resty-upstream-healthcheck/pull/87/commits/6b0fde522f679a62ce453f77fdfa75dae35523e1

2022-07-08 07:02 UTC, Freggy commented on lib/resty/upstream/healthcheck.lua
> +    bits[idx] = "# HELP nginx_upstream_status_info The running staus of nginx upstream"
see https://github.com/openresty/lua-resty-upstream-healthcheck/pull/87/commits/6b0fde522f679a62ce453f77fdfa75dae35523e1

2022-07-08 07:16 UTC, zhuizhuhaomeng requested changes

2022-07-08 07:16 UTC, zhuizhuhaomeng commented on lib/resty/upstream/healthcheck.lua
> +            bits[idx] = string.format("nginx_upstream_status_info{name=\"%s\",endpoint=\"%s\",status=\"UP\",role=\"%s\"} 1", u, peer.name, role)
```suggestion
        bits[idx] = string.format("nginx_upstream_status_info{name=\"%s\",endpoint=\"%s\",status=\"%s\",role=\"%s\"} 1", 
                      u, peer.name, peer.down and "DOWN" or "UP" role)
```

2022-07-08 07:29 UTC, Freggy commented on lib/resty/upstream/healthcheck.lua
> +            bits[idx] = string.format("nginx_upstream_status_info{name=\"%s\",endpoint=\"%s\",status=\"UP\",role=\"%s\"} 1", u, peer.name, role)
see https://github.com/openresty/lua-resty-upstream-healthcheck/pull/87/commits/63d01fa4f6cf5b3f2f77f67bdfffff1d1f4bca59

2022-07-25 10:49 UTC, Freggy commented
is there something missing still?

2022-07-27 11:15 UTC, zhuizhuhaomeng commented
> is there something missing still?

the CI failed.
```
Test Summary Report
-------------------
t/sanity.t (Wstat: 65280 Tests: 105 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 117 tests but ran 105.
Files=1, Tests=105, 11 wallclock secs ( 0.03 usr  0.00 sys +  0.85 cusr  0.13 csys =  1.01 CPU)
Result: FAIL
The command "prove -r t" exited with 1.
cache.2
store build cache
```

2022-07-27 11:24 UTC, zhuizhuhaomeng commented
> is there something missing still?

please move your test to another file 
eg: prometheus.t

2022-07-27 15:26 UTC, zhuizhuhaomeng commented
merged with the following patch
```
diff --git a/lib/resty/upstream/healthcheck.lua b/lib/resty/upstream/healthcheck.lua
index 5fcacd2..0099a59 100644
--- a/lib/resty/upstream/healthcheck.lua
+++ b/lib/resty/upstream/healthcheck.lua
@@ -657,7 +657,7 @@ local function gen_peers_prometheus_status_info(peers, bits, idx, u, role)
     for i = 1, npeers do
         idx = idx + 1
         local peer = peers[i]
-        bits[idx] = string.format("nginx_upstream_status_info{name=\"%s\",endpoint=\"%s\",status=\"%s\",role=\
"%s\"} 1", u, peer.name, peer.down and "DOWN" or "UP", role)   
+        bits[idx] = string.format("nginx_upstream_status_info{name=\"%s\",endpoint=\"%s\",status=\"%s\",role=\
"%s\"} 1", u, peer.name, peer.down and "DOWN" or "UP", role)
     end
     return idx
 end
diff --git a/t/prometheus.t b/t/prometheus.t
new file mode 100644
index 0000000..32fdb0b
--- /dev/null
+++ b/t/prometheus.t
@@ -0,0 +1,221 @@
+# vim:set ft= ts=4 sw=4 et fdm=marker:
+use lib 'lib';
+use Test::Nginx::Socket::Lua;
+use Cwd qw(cwd);
+
...
```

2022-07-27 15:26 UTC, closed without merging